# Prometheus configuration for monitoring Ollama applications
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ollama server monitoring
  - job_name: 'ollama-server'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Web application monitoring
  - job_name: 'ollama-webapp'
    static_configs:
      - targets: ['web-app:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # API server monitoring
  - job_name: 'ollama-api'
    static_configs:
      - targets: ['api-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
